<?php
// list icon
function efa_flaticon_icons(): array {
	return array(
		'flaticon-add' => 'Icon Add',
		'flaticon-add-1' => 'Icon Add 1',
		'flaticon-add-2' => 'Icon Add 2',
		'flaticon-add-3' => 'Icon Add 3',
		'flaticon-agenda' => 'Icon Agenda',
		'flaticon-alarm' => 'Icon Alarm',
		'flaticon-alarm-1' => 'Icon Alarm 1',
		'flaticon-alarm-clock' => 'Icon Alarm Clock',
		'flaticon-alarm-clock-1' => 'Icon Alarm Clock 1',
		'flaticon-albums' => 'Icon Albums',
		'flaticon-app' => 'Icon App',
		'flaticon-archive' => 'Icon Archive',
		'flaticon-archive-1' => 'Icon Archive 1',
		'flaticon-archive-2' => 'Icon Archive 2',
		'flaticon-archive-3' => 'Icon Archive 3',
		'flaticon-attachment' => 'Icon Attachment',
		'flaticon-back' => 'Icon Back',
		'flaticon-battery' => 'Icon Battery',
		'flaticon-battery-1' => 'Icon Battery 1',
		'flaticon-battery-2' => 'Icon Battery 2',
		'flaticon-battery-3' => 'Icon Battery 3',
		'flaticon-battery-4' => 'Icon Battery 4',
		'flaticon-battery-5' => 'Icon Battery 5',
		'flaticon-battery-6' => 'Icon Battery 6',
		'flaticon-battery-7' => 'Icon Battery 7',
		'flaticon-battery-8' => 'Icon Battery 8',
		'flaticon-battery-9' => 'Icon Battery 9',
		'flaticon-binoculars' => 'Icon Binoculars',
		'flaticon-blueprint' => 'Icon Blueprint',
		'flaticon-bluetooth' => 'Icon Bluetooth',
		'flaticon-bluetooth-1' => 'Icon Bluetooth 1',
		'flaticon-bookmark' => 'Icon Bookmark',
		'flaticon-bookmark-1' => 'Icon Bookmark 1',
		'flaticon-briefcase' => 'Icon Briefcase',
		'flaticon-broken-link' => 'Icon Broken Link',
		'flaticon-calculator' => 'Icon Calculator',
		'flaticon-calculator-1' => 'Icon Calculator 1',
		'flaticon-calendar' => 'Icon Calendar',
		'flaticon-calendar-1' => 'Icon Calendar 1',
		'flaticon-calendar-2' => 'Icon Calendar 2',
		'flaticon-calendar-3' => 'Icon Calendar 3',
		'flaticon-calendar-4' => 'Icon Calendar 4',
		'flaticon-calendar-5' => 'Icon Calendar 5',
		'flaticon-calendar-6' => 'Icon Calendar 6',
		'flaticon-calendar-7' => 'Icon Calendar 7',
		'flaticon-checked' => 'Icon Checked',
		'flaticon-checked-1' => 'Icon Checked 1',
		'flaticon-clock' => 'Icon Clock',
		'flaticon-clock-1' => 'Icon Clock 1',
		'flaticon-close' => 'Icon Close',
		'flaticon-cloud' => 'Icon Cloud',
		'flaticon-cloud-computing' => 'Icon Cloud Computing',
		'flaticon-cloud-computing-1' => 'Icon Cloud Computing 1',
		'flaticon-cloud-computing-2' => 'Icon Cloud Computing 2',
		'flaticon-cloud-computing-3' => 'Icon Cloud Computing 3',
		'flaticon-cloud-computing-4' => 'Icon Cloud Computing 4',
		'flaticon-cloud-computing-5' => 'Icon Cloud Computing 5',
		'flaticon-command' => 'Icon Command',
		'flaticon-compact-disc' => 'Icon Compact Disc',
		'flaticon-compact-disc-1' => 'Icon Compact Disc 1',
		'flaticon-compact-disc-2' => 'Icon Compact Disc 2',
		'flaticon-compass' => 'Icon Compass',
		'flaticon-compose' => 'Icon Compose',
		'flaticon-controls' => 'Icon Controls',
		'flaticon-controls-1' => 'Icon Controls 1',
		'flaticon-controls-2' => 'Icon Controls 2',
		'flaticon-controls-3' => 'Icon Controls 3',
		'flaticon-controls-4' => 'Icon Controls 4',
		'flaticon-controls-5' => 'Icon Controls 5',
		'flaticon-controls-6' => 'Icon Controls 6',
		'flaticon-controls-7' => 'Icon Controls 7',
		'flaticon-controls-8' => 'Icon Controls 8',
		'flaticon-controls-9' => 'Icon Controls 9',
		'flaticon-database' => 'Icon Database',
		'flaticon-database-1' => 'Icon Database 1',
		'flaticon-database-2' => 'Icon Database 2',
		'flaticon-database-3' => 'Icon Database 3',
		'flaticon-diamond' => 'Icon Diamond',
		'flaticon-diploma' => 'Icon Diploma',
		'flaticon-dislike' => 'Icon Dislike',
		'flaticon-dislike-1' => 'Icon Dislike 1',
		'flaticon-divide' => 'Icon Divide',
		'flaticon-divide-1' => 'Icon Divide 1',
		'flaticon-division' => 'Icon Division',
		'flaticon-document' => 'Icon Document',
		'flaticon-download' => 'Icon Download',
		'flaticon-edit' => 'Icon Edit',
		'flaticon-edit-1' => 'Icon Edit 1',
		'flaticon-eject' => 'Icon Eject',
		'flaticon-eject-1' => 'Icon Eject 1',
		'flaticon-equal' => 'Icon Equal',
		'flaticon-equal-1' => 'Icon Equal 1',
		'flaticon-equal-2' => 'Icon Equal 2',
		'flaticon-error' => 'Icon Error',
		'flaticon-exit' => 'Icon Exit',
		'flaticon-exit-1' => 'Icon Exit 1',
		'flaticon-exit-2' => 'Icon Exit 2',
		'flaticon-eyeglasses' => 'Icon Eyeglasses',
		'flaticon-fast-forward' => 'Icon Fast Forward',
		'flaticon-fast-forward-1' => 'Icon Fast Forward 1',
		'flaticon-fax' => 'Icon Fax',
		'flaticon-file' => 'Icon File',
		'flaticon-file-1' => 'Icon File 1',
		'flaticon-file-2' => 'Icon File 2',
		'flaticon-film' => 'Icon Film',
		'flaticon-fingerprint' => 'Icon Fingerprint',
		'flaticon-flag' => 'Icon Flag',
		'flaticon-flag-1' => 'Icon Flag 1',
		'flaticon-flag-2' => 'Icon Flag 2',
		'flaticon-flag-3' => 'Icon Flag 3',
		'flaticon-flag-4' => 'Icon Flag 4',
		'flaticon-focus' => 'Icon Focus',
		'flaticon-folder' => 'Icon Folder',
		'flaticon-folder-1' => 'Icon Folder 1',
		'flaticon-folder-10' => 'Icon Folder 10',
		'flaticon-folder-11' => 'Icon Folder 11',
		'flaticon-folder-12' => 'Icon Folder 12',
		'flaticon-folder-13' => 'Icon Folder 13',
		'flaticon-folder-14' => 'Icon Folder 14',
		'flaticon-folder-15' => 'Icon Folder 15',
		'flaticon-folder-16' => 'Icon Folder 16',
		'flaticon-folder-17' => 'Icon Folder 17',
		'flaticon-folder-18' => 'Icon Folder 18',
		'flaticon-folder-19' => 'Icon Folder 19',
		'flaticon-folder-2' => 'Icon Folder 2',
		'flaticon-folder-3' => 'Icon Folder 3',
		'flaticon-folder-4' => 'Icon Folder 4',
		'flaticon-folder-5' => 'Icon Folder 5',
		'flaticon-folder-6' => 'Icon Folder 6',
		'flaticon-folder-7' => 'Icon Folder 7',
		'flaticon-folder-8' => 'Icon Folder 8',
		'flaticon-folder-9' => 'Icon Folder 9',
		'flaticon-forbidden' => 'Icon Forbidden',
		'flaticon-funnel' => 'Icon Funnel',
		'flaticon-garbage' => 'Icon Garbage',
		'flaticon-garbage-1' => 'Icon Garbage 1',
		'flaticon-garbage-2' => 'Icon Garbage 2',
		'flaticon-gift' => 'Icon Gift',
		'flaticon-help' => 'Icon Help',
		'flaticon-hide' => 'Icon Hide',
		'flaticon-hold' => 'Icon Hold',
		'flaticon-home' => 'Icon Home',
		'flaticon-home-1' => 'Icon Home 1',
		'flaticon-home-2' => 'Icon Home 2',
		'flaticon-hourglass' => 'Icon Hourglass',
		'flaticon-hourglass-1' => 'Icon Hourglass 1',
		'flaticon-hourglass-2' => 'Icon Hourglass 2',
		'flaticon-hourglass-3' => 'Icon Hourglass 3',
		'flaticon-house' => 'Icon House',
		'flaticon-id-card' => 'Icon ID Card',
		'flaticon-id-card-1' => 'Icon ID Card 1',
		'flaticon-id-card-2' => 'Icon ID Card 2',
		'flaticon-id-card-3' => 'Icon ID Card 3',
		'flaticon-id-card-4' => 'Icon ID Card 4',
		'flaticon-id-card-5' => 'Icon ID Card 5',
		'flaticon-idea' => 'Icon Idea',
		'flaticon-incoming' => 'Icon Incoming',
		'flaticon-infinity' => 'Icon Infinity',
		'flaticon-info' => 'Icon Info',
		'flaticon-internet' => 'Icon Internet',
		'flaticon-key' => 'Icon Key',
		'flaticon-lamp' => 'Icon Lamp',
		'flaticon-layers' => 'Icon Layers',
		'flaticon-layers-1' => 'Icon Layers 1',
		'flaticon-like' => 'Icon Like',
		'flaticon-like-1' => 'Icon Like 1',
		'flaticon-like-2' => 'Icon Like 2',
		'flaticon-link' => 'Icon Link',
		'flaticon-list' => 'Icon List',
		'flaticon-list-1' => 'Icon List 1',
		'flaticon-lock' => 'Icon Lock',
		'flaticon-lock-1' => 'Icon Lock 1',
		'flaticon-locked' => 'Icon Locked',
		'flaticon-locked-1' => 'Icon Locked 1',
		'flaticon-locked-2' => 'Icon Locked 2',
		'flaticon-locked-3' => 'Icon Locked 3',
		'flaticon-locked-4' => 'Icon Locked 4',
		'flaticon-locked-5' => 'Icon Locked 5',
		'flaticon-locked-6' => 'Icon Locked 6',
		'flaticon-login' => 'Icon Login',
		'flaticon-magic-wand' => 'Icon Magic Wand',
		'flaticon-magnet' => 'Icon Magnet',
		'flaticon-magnet-1' => 'Icon Magnet 1',
		'flaticon-magnet-2' => 'Icon Magnet 2',
		'flaticon-map' => 'Icon Map',
		'flaticon-map-1' => 'Icon Map 1',
		'flaticon-map-2' => 'Icon Map 2',
		'flaticon-map-location' => 'Icon Map Location',
		'flaticon-megaphone' => 'Icon Megaphone',
		'flaticon-megaphone-1' => 'Icon Megaphone 1',
		'flaticon-menu' => 'Icon Menu',
		'flaticon-menu-1' => 'Icon Menu 1',
		'flaticon-menu-2' => 'Icon Menu 2',
		'flaticon-menu-3' => 'Icon Menu 3',
		'flaticon-menu-4' => 'Icon Menu 4',
		'flaticon-microphone' => 'Icon Microphone',
		'flaticon-microphone-1' => 'Icon Microphone 1',
		'flaticon-minus' => 'Icon Minus',
		'flaticon-minus-1' => 'Icon Minus 1',
		'flaticon-more' => 'Icon More',
		'flaticon-more-1' => 'Icon More 1',
		'flaticon-more-2' => 'Icon More 2',
		'flaticon-multiply' => 'Icon Multiply',
		'flaticon-multiply-1' => 'Icon Multiply 1',
		'flaticon-music-player' => 'Icon Music Player',
		'flaticon-music-player-1' => 'Icon Music Player 1',
		'flaticon-music-player-2' => 'Icon Music Player 2',
		'flaticon-music-player-3' => 'Icon Music Player 3',
		'flaticon-mute' => 'Icon Mute',
		'flaticon-muted' => 'Icon Muted',
		'flaticon-navigation' => 'Icon Navigation',
		'flaticon-navigation-1' => 'Icon Navigation 1',
		'flaticon-network' => 'Icon Network',
		'flaticon-newspaper' => 'Icon Newspaper',
		'flaticon-next' => 'Icon Next',
		'flaticon-note' => 'Icon Note',
		'flaticon-notebook' => 'Icon Notebook',
		'flaticon-notebook-1' => 'Icon Notebook 1',
		'flaticon-notebook-2' => 'Icon Notebook 2',
		'flaticon-notebook-3' => 'Icon Notebook 3',
		'flaticon-notebook-4' => 'Icon Notebook 4',
		'flaticon-notebook-5' => 'Icon Notebook 5',
		'flaticon-notepad' => 'Icon Notepad',
		'flaticon-notepad-1' => 'Icon Notepad 1',
		'flaticon-notepad-2' => 'Icon Notepad 2',
		'flaticon-notification' => 'Icon Notification',
		'flaticon-paper-plane' => 'Icon Paper Plane',
		'flaticon-paper-plane-1' => 'Icon Paper Plane 1',
		'flaticon-pause' => 'Icon Pause',
		'flaticon-pause-1' => 'Icon Pause 1',
		'flaticon-percent' => 'Icon Percent',
		'flaticon-percent-1' => 'Icon Percent 1',
		'flaticon-perspective' => 'Icon Perspective',
		'flaticon-photo-camera' => 'Icon Photo Camera',
		'flaticon-photo-camera-1' => 'Icon Photo Camera 1',
		'flaticon-photos' => 'Icon Photos',
		'flaticon-picture' => 'Icon Picture',
		'flaticon-picture-1' => 'Icon Picture 1',
		'flaticon-picture-2' => 'Icon Picture 2',
		'flaticon-pin' => 'Icon Pin',
		'flaticon-placeholder' => 'Icon Placeholder',
		'flaticon-placeholder-1' => 'Icon Placeholder 1',
		'flaticon-placeholder-2' => 'Icon Placeholder 2',
		'flaticon-placeholder-3' => 'Icon Placeholder 3',
		'flaticon-placeholders' => 'Icon Placeholders',
		'flaticon-play-button' => 'Icon Play Button',
		'flaticon-play-button-1' => 'Icon Play Button 1',
		'flaticon-plus' => 'Icon Plus',
		'flaticon-power' => 'Icon Power',
		'flaticon-previous' => 'Icon Previous',
		'flaticon-price-tag' => 'Icon Price Tag',
		'flaticon-print' => 'Icon Print',
		'flaticon-push-pin' => 'Icon Push Pin',
		'flaticon-radar' => 'Icon Radar',
		'flaticon-reading' => 'Icon Reading',
		'flaticon-record' => 'Icon Record',
		'flaticon-repeat' => 'Icon Repeat',
		'flaticon-repeat-1' => 'Icon Repeat 1',
		'flaticon-restart' => 'Icon Restart',
		'flaticon-resume' => 'Icon Resume',
		'flaticon-rewind' => 'Icon Rewind',
		'flaticon-rewind-1' => 'Icon Rewind 1',
		'flaticon-route' => 'Icon Route',
		'flaticon-save' => 'Icon Save',
		'flaticon-search' => 'Icon Search',
		'flaticon-search-1' => 'Icon Search 1',
		'flaticon-send' => 'Icon Send',
		'flaticon-server' => 'Icon Server',
		'flaticon-server-1' => 'Icon Server 1',
		'flaticon-server-2' => 'Icon Server 2',
		'flaticon-server-3' => 'Icon Server 3',
		'flaticon-settings' => 'Icon Settings',
		'flaticon-settings-1' => 'Icon Settings 1',
		'flaticon-settings-2' => 'Icon Settings 2',
		'flaticon-settings-3' => 'Icon Settings 3',
		'flaticon-settings-4' => 'Icon Settings 4',
		'flaticon-settings-5' => 'Icon Settings 5',
		'flaticon-settings-6' => 'Icon Settings 6',
		'flaticon-settings-7' => 'Icon Settings 7',
		'flaticon-settings-8' => 'Icon Settings 8',
		'flaticon-settings-9' => 'Icon Settings 9',
		'flaticon-share' => 'Icon Share',
		'flaticon-share-1' => 'Icon Share 1',
		'flaticon-share-2' => 'Icon Share 2',
		'flaticon-shuffle' => 'Icon Shuffle',
		'flaticon-shuffle-1' => 'Icon Shuffle 1',
		'flaticon-shutdown' => 'Icon Shutdown',
		'flaticon-sign' => 'Icon Sign',
		'flaticon-sign-1' => 'Icon Sign 1',
		'flaticon-skip' => 'Icon Skip',
		'flaticon-smartphone' => 'Icon Smartphone',
		'flaticon-smartphone-1' => 'Icon Smartphone 1',
		'flaticon-smartphone-10' => 'Icon Smartphone 10',
		'flaticon-smartphone-11' => 'Icon Smartphone 11',
		'flaticon-smartphone-2' => 'Icon Smartphone 2',
		'flaticon-smartphone-3' => 'Icon Smartphone 3',
		'flaticon-smartphone-4' => 'Icon Smartphone 4',
		'flaticon-smartphone-5' => 'Icon Smartphone 5',
		'flaticon-smartphone-6' => 'Icon Smartphone 6',
		'flaticon-smartphone-7' => 'Icon Smartphone 7',
		'flaticon-smartphone-8' => 'Icon Smartphone 8',
		'flaticon-smartphone-9' => 'Icon Smartphone 9',
		'flaticon-speaker' => 'Icon Speaker',
		'flaticon-speaker-1' => 'Icon Speaker 1',
		'flaticon-speaker-2' => 'Icon Speaker 2',
		'flaticon-speaker-3' => 'Icon Speaker 3',
		'flaticon-speaker-4' => 'Icon Speaker 4',
		'flaticon-speaker-5' => 'Icon Speaker 5',
		'flaticon-speaker-6' => 'Icon Speaker 6',
		'flaticon-speaker-7' => 'Icon Speaker 7',
		'flaticon-speaker-8' => 'Icon Speaker 8',
		'flaticon-spotlight' => 'Icon Spotlight',
		'flaticon-star' => 'Icon Star',
		'flaticon-star-1' => 'Icon Star 1',
		'flaticon-stop' => 'Icon Stop',
		'flaticon-stop-1' => 'Icon Stop 1',
		'flaticon-stopwatch' => 'Icon Stopwatch',
		'flaticon-stopwatch-1' => 'Icon Stopwatch 1',
		'flaticon-stopwatch-2' => 'Icon Stopwatch 2',
		'flaticon-stopwatch-3' => 'Icon Stopwatch 3',
		'flaticon-stopwatch-4' => 'Icon Stopwatch 4',
		'flaticon-street' => 'Icon Street',
		'flaticon-street-1' => 'Icon Street 1',
		'flaticon-substract' => 'Icon Substract',
		'flaticon-substract-1' => 'Icon Substract 1',
		'flaticon-success' => 'Icon Success',
		'flaticon-switch' => 'Icon Switch',
		'flaticon-switch-1' => 'Icon Switch 1',
		'flaticon-switch-2' => 'Icon Switch 2',
		'flaticon-switch-3' => 'Icon Switch 3',
		'flaticon-switch-4' => 'Icon Switch 4',
		'flaticon-switch-5' => 'Icon Switch 5',
		'flaticon-switch-6' => 'Icon Switch 6',
		'flaticon-switch-7' => 'Icon Switch 7',
		'flaticon-tabs' => 'Icon Tabs',
		'flaticon-tabs-1' => 'Icon Tabs 1',
		'flaticon-target' => 'Icon Target',
		'flaticon-television' => 'Icon Television',
		'flaticon-television-1' => 'Icon Television 1',
		'flaticon-time' => 'Icon Time',
		'flaticon-trash' => 'Icon Trash',
		'flaticon-umbrella' => 'Icon Umbrella',
		'flaticon-unlink' => 'Icon Unlink',
		'flaticon-unlocked' => 'Icon Unlocked',
		'flaticon-unlocked-1' => 'Icon Unlocked 1',
		'flaticon-unlocked-2' => 'Icon Unlocked 2',
		'flaticon-upload' => 'Icon Upload',
		'flaticon-user' => 'Icon User',
		'flaticon-user-1' => 'Icon User 1',
		'flaticon-user-2' => 'Icon User 2',
		'flaticon-user-3' => 'Icon User 3',
		'flaticon-user-4' => 'Icon User 4',
		'flaticon-user-5' => 'Icon User 5',
		'flaticon-user-6' => 'Icon User 6',
		'flaticon-user-7' => 'Icon User 7',
		'flaticon-users' => 'Icon Users',
		'flaticon-users-1' => 'Icon Users 1',
		'flaticon-video-camera' => 'Icon Video Camera',
		'flaticon-video-camera-1' => 'Icon Video Camera 1',
		'flaticon-video-player' => 'Icon Video Player',
		'flaticon-video-player-1' => 'Icon Video Player 1',
		'flaticon-video-player-2' => 'Icon Video Player 2',
		'flaticon-view' => 'Icon View',
		'flaticon-view-1' => 'Icon View 1',
		'flaticon-view-2' => 'Icon View 2',
		'flaticon-volume-control' => 'Icon Volume Control',
		'flaticon-volume-control-1' => 'Icon Volume Control 1',
		'flaticon-warning' => 'Icon Warning',
		'flaticon-wifi' => 'Icon Wifi',
		'flaticon-wifi-1' => 'Icon Wifi 1',
		'flaticon-windows' => 'Icon Windows',
		'flaticon-windows-1' => 'Icon Windows 1',
		'flaticon-windows-2' => 'Icon Windows 2',
		'flaticon-windows-3' => 'Icon Windows 3',
		'flaticon-windows-4' => 'Icon Windows 4',
		'flaticon-wireless-internet' => 'Icon Wireless Internet',
		'flaticon-worldwide' => 'Icon Worldwide',
		'flaticon-worldwide-1' => 'Icon Worldwide 1',
		'flaticon-zoom-in' => 'Icon Zoom In',
		'flaticon-zoom-out' => 'Icon Zoom Out'
	);
}

// html tag heading
function efa_html_tag_heading(): array {
	return [
		'h1' => 'H1',
		'h2' => 'H2',
		'h3' => 'H3',
		'h4' => 'H4',
		'h5' => 'H5',
		'h6' => 'H6'
	];
}

// Get Category Check Box
function efa_check_get_cat( $type_taxonomy ): array {
	$cat_check = array();
	$category  = get_terms(
		array(
			'taxonomy'   => $type_taxonomy,
			'hide_empty' => false
		)
	);

	if ( ! empty( $category ) ):
		foreach ( $category as $item ) {
			$cat_check[ $item->term_id ] = $item->name;
		}
	endif;

	return $cat_check;
}

// Get Contact Form 7
function efa_get_form_cf7(): array {
	$options = array();

	if ( function_exists( 'wpcf7' ) ) {

		$wpcf7_form_list = get_posts( array(
			'post_type'   => 'wpcf7_contact_form',
			'numberposts' => - 1,
		) );

		$options[0] = esc_html__( 'Select a Contact Form', 'essential-features-addon' );

		if ( ! empty( $wpcf7_form_list ) && ! is_wp_error( $wpcf7_form_list ) ) :
			foreach ( $wpcf7_form_list as $item ) :
				$options[ $item->ID ] = $item->post_title;
			endforeach;
		else :
			$options[0] = esc_html__( 'Create a Form First', 'essential-features-addon' );
		endif;

	}

	return $options;
}

// image size options
function efa_image_size_options(): array
{
	return [
		'thumbnail' => esc_html__('Thumbnail (150 x 150)', 'essential-features-addon'),
		'medium' => esc_html__('Medium(300 x 300)', 'essential-features-addon'),
		'medium_large' => esc_html__('Medium Large(768 x 0)', 'essential-features-addon'),
		'large' => esc_html__('Large(1024 x 1024)', 'essential-features-addon'),
		'full' => esc_html__('Full Size(Kích thước gốc)', 'essential-features-addon'),
	];
}

// image object position
function efa_image_object_position_options(): array {
	return [
		'center center' => esc_html__( 'Chính giữa', 'essential-features-addon' ),
		'center left' => esc_html__( 'Ở giữa bên trái', 'essential-features-addon' ),
		'center right' => esc_html__( 'Ở giữa bên phải', 'essential-features-addon' ),
		'top center' => esc_html__( 'Trên cùng ở giữa', 'essential-features-addon' ),
		'top left' => esc_html__( 'Trên cùng bên trái', 'essential-features-addon' ),
		'top right' => esc_html__( 'Trên cùng bên phải', 'essential-features-addon' ),
		'bottom center' => esc_html__( 'Phía dưới ở giữa', 'essential-features-addon' ),
		'bottom left' => esc_html__( 'Phía dưới bên trái', 'essential-features-addon' ),
		'bottom right' => esc_html__( 'Phía dưới bên phải', 'essential-features-addon' ),
	];
}

// pagination
function efa_pagination(): void {
	the_posts_pagination( array(
		'type'               => 'list',
		'mid_size'           => 2,
		'prev_text'          => esc_html__( 'Trước', 'essential-features-addon' ),
		'next_text'          => esc_html__( 'Sau', 'essential-features-addon' ),
		'screen_reader_text' => '&nbsp;',
	) );
}

// replace number
function efa_preg_replace_ony_number( $string ): string|null {
	$number = '';

	if ( ! empty( $string ) ) {
		$number = preg_replace( '/[^0-9]/', '', strip_tags( $string ) );
	}

	return $number;
}